# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeside < Formula
  desc "A Kubernetes client scoped to the developer, not the cluster operator"
  homepage "https://github.com/dynaum/kubeside"
  version "1.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dynaum/kubeside/releases/download/v1.2.0/kubeside_1.2.0_darwin_amd64.tar.gz"
      sha256 "02c6c9f2ec6bcc2dc3644c612b9054ed21c4605c35c7d7d2d0b4218326d5a9d1"

      define_method(:install) do
        bin.install "kubeside"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dynaum/kubeside/releases/download/v1.2.0/kubeside_1.2.0_darwin_arm64.tar.gz"
      sha256 "65cc69e36ff24d06adabc3838e9f0d4a72334ea4c21ed6d9315dda0b6f158533"

      define_method(:install) do
        bin.install "kubeside"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dynaum/kubeside/releases/download/v1.2.0/kubeside_1.2.0_linux_amd64.tar.gz"
      sha256 "7f1fa4da86cdd7587d9e1a627d73fe982863709e4bf8db7c84448c5dbf28557c"
      define_method(:install) do
        bin.install "kubeside"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dynaum/kubeside/releases/download/v1.2.0/kubeside_1.2.0_linux_arm64.tar.gz"
      sha256 "bb34f2b5970a5865e5952c550ced4d3007ef6acfec890a127a61575bd612f0a8"
      define_method(:install) do
        bin.install "kubeside"
      end
    end
  end

  test do
    system "#{bin}/kubeside", "--version"
  end
end
